config/routes.rb
Rails.application.routes.draw do

  resources :categories
  # devise_for :users
  resources :places
  resources :events
  get 'import/events', to: 'events#import', as: :import_events
  get 'import/places', to: 'places#import', as: :import_places
  match '/events/get_address_and_loc' => 'events#get_address_and_loc', :via => :post


  root 'pages#home'
  get 'pages/dates'
  get 'pages/user_index'
  get 'pages/sample_user'
  get 'pages/explore'
  get 'pages/dating'
  get 'pages/bundle_9786063511'
  get '/adventures', to: 'pages#adventures'
  get '/rec', to: 'pages#rec'
  get '/another', to: 'pages#another'
  get '/join', to: 'pages#join'
  get '/test', to: 'pages#test'
  get '/postcard', to: 'pages#postcard'

  # ANALYTICS DASHBOARD
  get '/dashboard', to: 'dashboard#index', as: :dashboard
  match '/dashboard/metrics' => 'dashboard#metrics', :via => :post

  # FRONT WEBHOOK
  match '/front/mirror' => 'front#mirror', :via => :post
  match '/front/bot' => 'front#bot', :via => :post
end

app/views/shared/_error_messages.html.erb
<% if @event.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@event.errors.count, "error") %>.
    </div>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_eventCard.erb
<div class="four wide column">

  <!-- event image -->
  <div class="event-preview" style="background: url(<%= instance.event.image.url(:medium) %>);">
 
    <!-- container for color overlay -->
    <div class="event-preview-inside">

      <!-- event date -->
      <p class="event-preview-date">
        <span><%= instance.date.strftime("%a") %></span>
        <br>
        <%= instance.date.strftime("%b %d") %>
      </p>

      <button class="ui icon mini button right floated copy-to-clipboard" data-clipboard-text="<%= instance.event.short_blurb %> More info here: www.joinferris.com/events/<%= instance.event_id %>">
        <i class="copy icon"></i>
      </button>

      <!-- event header -->
      <%= link_to event_path(instance.event) do %>
        <div class="event-preview-text">
          <h4>
            <%= instance.event.title %>
          </h4>
          <p class="event-preview-meta">
            <% unless instance.event.place.nil? %>
              <% if instance.event.place.neighborhood? %>
                <%= instance.event.place.neighborhood %>
              <% else %>
                <%= instance.event.place.city if instance.event.place.city? %>
              <% end %>
            <% end %>
            ·
            <% if instance.event.price == 0 || instance.event.price.nil? %>
              Free
            <% else %>
              $<%= instance.event.price %>.00
            <% end %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  var clipboard = new Clipboard('.copy-to-clipboard');
  clipboard.on('success', function(e) {
    console.info('Action:', e.action);
    console.info('Text:', e.text);
    console.info('Trigger:', e.trigger);

    e.clearSelection();
  });

  clipboard.on('error', function(e) {
      console.error('Action:', e.action);
      console.error('Trigger:', e.trigger);
  });
</script>

app/views/shared/_footer.erb
<div class="ui four item menu" id="footer">
  <div class="ui upward dropdown link item" id="when-select">
    <i class="large calendar icon"></i>
    <span class="text">Date</span>
    <div class="menu">
        <div class="item" data-value="1">
          Today
        </div>
        <div class="item" data-value="2">
          Tomorrow
        </div>
        <div class="item" data-value="3">
          This Week
        </div>
        <div class="item" data-value="4">
          This Weekend
        </div>
    </div>
  </div>
  <div class="ui scrolling upward dropdown link item" id="where-select">
    <i class="large map icon"></i>
    <span class="text">Location</span>
    <div class="menu">
      <div class="item" data-value="-3">
        Boston
      </div>
      <div class="item" data-value="-2">
        Cambridge
      </div>
      <div class="item" data-value="-1">
        Somerville
      </div>
      <div class="divider"></div>
      <% Place.all.order(:neighborhood).pluck(:neighborhood).uniq.each_with_index do |hood, i| %>
        <% unless hood.blank? %>
          <div class="item" data-value=<%= i %>>
            <%= hood %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="ui scrolling upward dropdown link item" id="categories-select">
    <i class="large tag icon"></i>
    <span class="text">Categories</span>
    <div class="menu">
      <% Category.all.order(:name).uniq.each do |category| %>
        <div class="item" data-value=<%= category.name %>>
        <% if category.icon? %>
            <i class="<%= category.icon %> icon"></i>
            <%= category.name %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <a class="item" id="search-button">
    Filter
  </a>
</div>

<script>
  $('.dropdown')
    .dropdown({
      direction: 'upward'
    })
  ;
</script>

app/views/shared/_futureFooter.erb
<div class="ui three item menu" id="footer">
  <div class="ui upward dropdown link item" id="when-select">
    <span class="text">
      <i class="large calendar icon"></i> Date
    </span>
    <div class="menu">
        <div class="item" data-value="1">
          Today
        </div>
        <div class="item" data-value="2">
          Tomorrow
        </div>
        <div class="item" data-value="3">
          This Week
        </div>
        <div class="item" data-value="4">
          This Weekend
        </div>
    </div>
  </div>
  <div class="ui scrolling upward dropdown link item" id="where-select">
    <span class="text">
      <i class="large map icon"></i> Location
    </span>
    <div class="menu">
      <div class="item" data-value="-3">
        Boston
      </div>
      <div class="item" data-value="-2">
        Cambridge
      </div>
      <div class="item" data-value="-1">
        Somerville
      </div>
      <div class="divider"></div>
      <% Place.all.order(:neighborhood).pluck(:neighborhood).uniq.each_with_index do |hood, i| %>
        <% unless hood.blank? %>
          <div class="item" data-value=<%= i %>>
            <%= hood %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <!--
  <div class="ui scrolling upward dropdown link item" id="categories-select">
    <span class="text">
      <i class="large tag icon"></i> Categories
    </span>
    <div class="menu">
      <% Category.all.order(:name).uniq.each do |category| %>
        <div class="item" data-value=<%= category.name %>>
        <% if category.icon? %>
            <i class="<%= category.icon %> icon"></i>
            <%= category.name %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  -->
  <a class="item" id="search-button">
    Filter
  </a>
</div>

<script>
  $('.dropdown')
    .dropdown({
      direction: 'upward'
    })
  ;
</script>

app/views/shared/_header.erb
<div class="ui fixed text menu" style="padding: 5px 10px; background-color: white;">
  <div class="item">
    <%= image_tag("logo-face-only.png") %>
  </div>
  <div class="right menu">
    <div class="item">
      <a href="/">
        Text Ferris
      </a>
      <!--
      <div class="ui icon input">
        <input type="text" placeholder="Search...">
        <i class="search link icon"></i>
      </div>
      -->
    </div>
  </div>
</div>

app/views/shared/_importCard.erb
<div class="four wide column">
  <div class="ui cards preview-card">
    <div class="card">

      <!-- Use event's place image if event has no image -->
      <% if instance.event.image? %>
        <%= link_to image_tag(instance.event.image.url(:banner), class: "index-image"), edit_event_path(instance.event) %>
      <% elsif instance.event.place.image? %>
        <%= link_to image_tag(instance.event.place.image.url(:banner), class: "index-image"), edit_event_path(instance.event) %>
      <% end %>

      <div class="content">
        <!-- Title-->
        <div class="header"><%= link_to (instance.event.title), edit_event_path(instance.event) %></div>
        <!-- Date -->
        <div class="meta">
          <% if instance.date.today? %>
            Today, <%= instance.event.start_time.strftime("%l:%M%P") %>
            <%= '- '+instance.event.end_time.strftime("%l:%M %P") unless instance.event.end_time.nil? %>
          <% else %>
            <%= instance.date.strftime("%a. %-m/%d") %>,
            <%= instance.event.start_time.strftime("%l:%M%P") %>
            <%= '- '+instance.event.end_time.strftime("%l:%M %P") unless instance.event.end_time.nil? %>
          <% end %>
        </div>
        <!-- Blurb -->
        <div class="description">
          <%= truncate(instance.event.short_blurb, length: 105, seperator: ' ', omission: '...') %>
        </div>
      </div>

      <!-- Footer -->
      <div class="extra content">
                <span class="right floated">
                  <button class="ui mini basic labeled icon button copy-to-clipboard" data-clipboard-text="<%= instance.event.short_blurb %> More info here: www.joinferris.com/events/<%= instance.event_id %>">
                    <i class="copy icon"></i>
                    Copy
                  </button>
                </span>
                <span>
                  <% unless instance.event.place.nil? %>
                    <i class="globe icon"></i>
                    <% if instance.event.place.neighborhood? %>
                      <%= instance.event.place.neighborhood %>
                    <% else %>
                      <%= instance.event.place.city if instance.event.place.city? %>
                    <% end %>
                  <% end %>
                </span>
      </div>
    </div>
  </div>
</div>

app/views/shared/_mixpanel.html.erb
<!-- start Mixpanel -->
<script type="text/javascript">(function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
	
	for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f)}})(document,window.mixpanel||[]);
	mixpanel.init("102cf58192ef1e319bf6cb10a6c281f8");
</script>
<!-- end Mixpanel -->
<script type="text/javascript">
	mixpanel.track('page viewed', {
	    'page name' : document.title,
	    'url' : window.location.pathname
	});
</script>