config/routes.rb
Rails.application.routes.draw do

  resources :categories
  # devise_for :users
  resources :places
  resources :events
  get 'import/events', to: 'events#import', as: :import_events
  get 'import/places', to: 'places#import', as: :import_places
  match '/events/get_address_and_loc' => 'events#get_address_and_loc', :via => :post


  root 'pages#home'
  get 'pages/dates'
  get 'pages/user_index'
  get 'pages/sample_user'
  get 'pages/explore'
  get 'pages/dating'
  get 'pages/bundle_9786063511'
  get '/adventures', to: 'pages#adventures'
  get '/rec', to: 'pages#rec'
  get '/another', to: 'pages#another'
  get '/join', to: 'pages#join'
  get '/test', to: 'pages#test'
  get '/postcard', to: 'pages#postcard'

  # ANALYTICS DASHBOARD
  get '/dashboard', to: 'dashboard#index', as: :dashboard
  match '/dashboard/metrics' => 'dashboard#metrics', :via => :post

  # FRONT WEBHOOK
  match '/front/mirror' => 'front#mirror', :via => :post
  match '/front/bot' => 'front#bot', :via => :post
end

app/models/event.rb
class Event < ActiveRecord::Base
  before_save :sanitize_urls
  after_save :generate_recurrences

  has_many :occurrences, -> { order(date: :asc) }, dependent: :destroy
  belongs_to :category
  belongs_to :place

  serialize :recurrence, Hash

	# form validations
	validates :title, presence: true
	# validates :short_blurb, presence: true
	# validates :description, presence: true
	# validates :address, presence: true
	# validates :price, numericality: { only_integer: true }

	#validate :event_date_cannot_be_in_the_past
	#validate :event_end_time_cannot_be_before_start_time

	# image upload properties
	has_attached_file :image, styles: {
		medium: '400x300#',
		banner: '338x100#',
		tiny: '140x140>',
		mini: '80x80!'
	}
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  # parse recurrence and save as schedule
  def recurrence=(new_rule)
    if RecurringSelect.is_valid_rule?(new_rule)
      rule = RecurringSelect.dirty_hash_to_rule(new_rule).to_hash
      write_attribute(:recurrence, rule)
    else
      write_attribute(:recurrence, nil)
    end
  end

  # custom getter to convert hash into schedule
  def recurrence
    unless read_attribute(:recurrence).empty?
      IceCube::Rule.from_hash(read_attribute(:recurrence))
    end
  end

  # on creation or update, generate event instances
  def generate_recurrences
    # remove all already scheduled occurrences in the future
    Occurrence.where('event_id = ? AND date >= ?', self.id, Date.current).delete_all
    
    if read_attribute(:recurrence).empty?
      Occurrence.create(event: self, date: self.date)
    else
      # schedule events for the next month
      # TODO: make instance variable with schedule instance to avoid repeat instantiation
      schedule = IceCube::Schedule.new
      schedule.add_recurrence_rule(self.recurrence)
      schedule.occurrences(Time.current + 1.month).each do |o|
        Occurrence.create(event: self, date: o.to_date)
      end
    end
  end

	# search for event by a user's preferences in a conversation
	def self.recommend(convo)
    ids = Occurrence.where(date: convo.pref_begin_time..convo.pref_end_time).map {|o| o.event.id}

    if convo.pref_location?
      events = Event.where(id: ids).joins(:place).where('places.neighborhood || places.city ILIKE ?', "%#{convo.pref_location}%")
    else
      events = Event.where(id: ids)
    end

    all_events = []
    if convo.pref_categories?
      tags = convo.pref_categories.split(',')
      tags.each do |tag|
        (all_events << events.joins(place: :tags).where('tags.name ILIKE ?', "%#{tag}%")).flatten!
      end
    end

    return all_events unless all_events.empty?
    return events unless events.empty?

    #  now search descriptions
    if convo.pref_categories?
      tags = convo.pref_categories.split(',')
      tags.each do |tag|
        (all_events << events.where('events.description || events.short_blurb ILIKE ?', "%#{tag}%")).flatten!
      end
    end

    return all_events

	end

	def sanitize_urls
	  unless  self.website.nil? || self.website.include?('http://') || self.website.include?('https://')
	      self.website = 'http://' + self.website
    end

    unless self.purchase_url.nil? || self.purchase_url.include?('http://') || self.purchase_url.include?('https://')
      self.purchase_url = 'http://' + self.purchase_url
    end
  end

  # get the next occurrence of an event
  def next
    self.occurrences.where('date >= ?', Date.current).first
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    # authenticate

    # Parse Filters from Nav Bar

    # DATE RANGE
    period = 5 # default is next 2 weeks
    if params[:when]
      period = params[:when].to_i
    end

    case period
      when 1 # Today
        range = Date.current
      when 2 # Tomorrow
        range = Date.current.tomorrow
      when 3 # This Week
        range = Date.current..Date.current.at_end_of_week
      when 4 # This Weekend
        range = Date.current.at_end_of_week - 2.days..Date.current.at_end_of_week
      when 5 # Next Two Weeks
        range = Date.current..Date.current + 2.weeks
    end

    @event_instances = Occurrence.limit(300).joins(:event).where('events.approved = true').order('date', 'events.start_time')

    # LOCATION
    # if Boston, Cambridge, Somerville: all events with place.city == "Boston"
    if params[:where]
      location = params[:where]
      if location == 'Boston' || location == 'Cambridge' || location == 'Somerville'
        @event_instances = @event_instances.joins(event: :place).where('places.city = ?', location)
      else
        @event_instances = @event_instances.joins(event: :place).where('places.neighborhood = ?', location)
      end
    end

    # CATEGORIES
    if params[:what]
      categories = params[:what].split(',')
      @event_instances = @event_instances.joins(event: :category).where('categories.name in (?)', categories)
    end

    js :URL => request.original_url.split('?').first, :when => period, :where => location, :what => categories
  end

  def import
    # authenticate

    if params[:search]
      events = Event.where(approved: false).includes(:occurrences, :place).search(params[:search])
    else
      events = Event.where(approved: false).includes(:occurrences, :place).order(interested_count: :desc)
    end

    # TODO: will this be efficient for 500+ events?
    @event_instances = events.map { |e| e.occurrences }.flatten!#.sort_by {|o| [o.date, o.event.start_time]}
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    js :URL => request.base_url
  end

  # GET /events/1/edit
  def edit
    js :new, :URL => request.base_url # execute same javascript as new
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    # if the event was unapproved, add it to our import blacklist
    unless @event.approved?
      Blacklist.create(fb_id: @event.fb_id, name: @event.title)
    end

    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # input is place_id, output is address and location strings in a json hash
  def get_address_and_loc
    id = params[:place_id].to_i
    place = Place.find(id)
    render json: { address: place.address, loc: place.neighborhood }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:title, :description, :place_id, :category_id, :date, :start_time, :end_time, :address, :neighborhood, :website, :price, :purchase_url, :image, :short_blurb, :recurrence, :approved)
  end
end

app/helpers/events_helper.rb
module EventsHelper

end

app/views/events/_error_messages.html.erb
<% if @event.errors.any? %>
  <div class="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@event.errors.count, "error") %>.
    </div>
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/events/_event_header.html.erb
<div class="ui secondary fluid one item menu">
  <a class="item" href="http://www.joinferris.com/">
    <%= image_tag("logo-white-background.png", :class => "ui centered image tiny") %>
  </a>
</div>

app/views/events/_form.html.erb
<div id="new-event-form">
  <div class="ui form">
    <div style="margin-bottom: 2em;">
      <h3 style="text-align: center">
        List My Event
      </h3>
      <p style="font-size: 1em; margin-top: 1em">
        Ferris is a free marketing tool to promote your events to a local, engaged audience in Boston. Every day, hundreds of people text Ferris looking for something to do in Boston. Our human-assisted algorithm will recommend events and venues to people's interests, all through text messaging. All you have to do to have your events promoted is to add them to our database by filling out the form below.
      </p>
    </div>
    <%= simple_form_for @event, html: { multipart: true } do |f| %>
      <%= render 'error_messages' %>
      <div class="field">
        <%= f.label :image %><br>
        <%= f.file_field :image, html: { class: 'form-control' } %>
        <% if f.object.image? %>
            <br />
            <%= image_tag(f.object.image.url(:medium)) %><br />
            <em>Currently Uploaded Image</em>
        <% end %>
      </div>
      <div class="field">
        <%= f.label :title, required: false %><br>
        <%= f.text_field :title, class: "ui input" %>
      </div>
      <div class="field">
        <%= f.label :short_blurb, required: false %><br>
        <%= f.text_area :short_blurb, class: "ui input" %>
      </div>
      <div class="field">
        <%= f.label :description, required: false %><br>
        <%= f.text_area :description, class: "ui input" %>
      </div>
      <div class="field">
        <%= f.label :date %><br>
        <%= f.date_select :date %>
      </div>
      <div class="field">
        <%= f.label :start_time %><br>
        <%= f.time_select :start_time, {:minute_step => 15, :ampm => true} %>
      </div>
      <div class="field">
        <%= f.label :end_time %><br>
        <%= f.time_select :end_time, {:minute_step => 15, :ampm => true} %>
      </div>
      <div class="field">
        <%= f.label :recurrence %><br>
        <%= f.select_recurring :recurrence %>
      </div>
      <div class="field">
        <%= f.label 'Place'%><br>
        <%= f.association :place, label: false, collection: Place.order(:name), label_method: :name, value_method: :id, prompt: 'None' %>
      </div>
      <% unless @event.place.nil? %>
        <%= link_to @event.place.name, place_path(@event.place), class: "ui blue fluid button" %>
      <% end %>
      <br/>
      <div class="field">
        <%= f.label 'Category'%><br>
        <%= f.association :category, label: false, collection: Category.order(:name), label_method: :name, value_method: :id, prompt: 'None' %>
      </div>
      <div class="field">
        <%= f.label :website %>
        <div class="ui labeled input">
          <div class="ui label">
            http://
          </div>
          <%= f.text_field :website, :placeholder => "mywebsite.com" %>
        </div>
      </div>
      <div class="field">
        <%= f.label :price %>
        <div class="ui right labeled input">
          <div class="ui label">$</div>
          <%= f.text_field :price %>
          <div class="ui basic label">.00</div>
        </div>
      </div>
      <div class="field">
        <%= f.label :ticket_purchase_link %>
        <div class="ui labeled input">
          <div class="ui label">
            http://
          </div>
          <%= f.text_field :purchase_url, :placeholder => "(optional)" %>
        </div>
      </div>
      <div class="field">
        <% unless @event.approved? %>
          <%= f.input :approved, as: :boolean %>
        <% end %>
      </div>
      <% if not @event.approved? %>
        <%= f.submit 'Approve', class: "ui blue fluid button", name: 'approve' %>
      <% else %>
        <%= f.submit 'Create', class: "ui blue fluid button", name: 'create' %>
      <% end %>
      <br/>
      <% unless @event.new_record? %>
        <%= link_to 'Delete', event_path(@event), :method => :delete, class: "ui blue fluid button" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/events/_header.html.erb
<div class="ui secondary fluid three item menu">
  <div class="ui item 3 column grid">
    <div class="row">
      <select id="date_range" class="ui dropdown">
        <option value="">Select Date Range</option>
        <option value="1">Today</option>
        <option value="2">Tomorrow</option>
        <option value="3">This Week</option>
        <option value="4">This Weekend</option>
        <option value="5">Next Two Weeks</option>
      </select>
    </div>
    <div class="row">
      <select id="tag_select" class="ui search dropdown" multiple="">
        <option value="">Select Tags</option>
        <% Tag.all.each_with_index do |t,i=1| %>
          <%= options_for_select([[t.name.titleize, i]]) %>
        <% end %>
      </select>
      <button id="tag_search" class="ui icon button right floated">
        <i class="search icon"></i>
      </button>
    </div>
  </div>
  <a class="ui item hidden" href="#" id="remove-icon">
    <i class="remove icon"></i>
  </a>
  <a class="item" href="./">
    <%= image_tag("face.png", :class => "ui centered image mini") %>
  </a>
  <a class="ui item" href="/events/new">
    <i class="plus icon"></i>
  </a>
</div>

<div class="ui secondary menu hidden" id="search-form">
  <div class="centered item">
    <div class="ui icon input">
      <%= form_tag(events_path, :method => "get") do %>
         <%= text_field_tag :search, params[:search], placeholder: "Search Events" %>
         <%= submit_tag "Search" %>
      <% end %>
      <i class="search link icon"></i>
    </div>
  </div>
</div>

<script>
  $('select.dropdown').dropdown();
</script>

app/views/events/_new_event_header.html.erb
<div class="ui secondary fluid three item menu">
  <a class="ui item invisible" href="./">
    <i class="remove icon"></i>
  </a>
  <a class="item" href="../">
    <%= image_tag("face.png", :class => "ui centered image mini") %>
  </a>
  <a class="ui item invisible" href="#">
    <i class="plus icon"></i>
  </a>
</div>

app/views/events/edit.html.erb
<%= render 'new_event_header' %>
<%= render 'form' %>
<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/import.html.erb
<% provide(:title, ' | Events') %>
<br/>
<div class="three wide column">
  <div class="ui statistic">
    <div class="label">
      Unapproved Events
    </div>
    <div id="events_left" class="value">
      <%= Event.where(approved: false).count %>
    </div>
  </div>
</div>

<% if @event_instances.nil? %>
  <div class="twelve wide column">
    No Events in Queue
  </div>
<% end %>
<div class="ui padded grid stackable">
  <% @event_instances.to_a.each do |instance| %>
      <%= render(:partial => 'shared/importCard', :locals => {:instance => instance})%>
  <% end %>
</div>

<script>
  var clipboard = new Clipboard('.copy-to-clipboard');
  clipboard.on('success', function(e) {
    console.info('Action:', e.action);
    console.info('Text:', e.text);
    console.info('Trigger:', e.trigger);

    e.clearSelection();
  });

  clipboard.on('error', function(e) {
    console.error('Action:', e.action);
    console.error('Trigger:', e.trigger);
  });
</script>

app/views/events/index.html.erb
<% provide(:title, ' | Events') %>
<%= render 'shared/header' %>

<div class="ui stackable grid" style="margin-top: 20px">
  <% @event_instances.each do |instance| %>
      <%= render(:partial => 'shared/eventCard', :locals => {:instance => instance})%>
  <% end %>
</div>

<%= render 'shared/footer' %>

app/views/events/new.html.erb
<% provide(:title, ' | Create New Event') %>
<%= render 'new_event_header' %>
<%= render 'form' %>

app/views/events/show.html.erb
<% provide(:title, ' | ' + @event.title) %>
<%= render 'event_header' %>
<div class="event-card">
  <div class="ui card">
    <div class="ui fluid image">
      <%= image_tag @event.image.url(:medium), class: "index-image" %>
    </div>
    <div class="content">
      <p class="header"><%= @event.title %></p>
      <div class="meta">
        <% if @event.recurrence? %>
          <span class="date"><i class="calendar icon"></i> <%= @event.recurrence.to_s %></span>
        <% elsif @event.date.today? %>
          <span class="date"><i class="calendar icon"></i> Today</span>
        <% else %>
          <span class="date"><i class="calendar icon"></i> <%= @event.date.strftime("%A, %B %d") %></span>
        <% end %>
        <br>
        <span class="date"><i class="wait icon"></i>
          <%= @event.start_time.strftime("%l:%M%P") %>
          <%= '- '+@event.end_time.strftime("%l:%M%P") unless @event.end_time.nil? %></span>
      </div>
      <div class="description">
        <%= @event.description %>

      </div>
    </div>
    <% unless @event.place.nil? %>
        <div class="extra content">
          <a href="http://maps.google.com/?q=<%= @event.place.address %>" target="_blank">
            <i class="location arrow icon"></i>
            <% if @event.place.neighborhood? %>
                <%= @event.place.neighborhood %>
            <% else %>
                <%= @event.place.city if @event.place.city? %>
            <% end %>
          </a>
        </div>
    <% end %>
    <div class="extra content">
      <a href="<%= @event.website %>" target="_blank">
        <i class="linkify icon"></i>
        Read More
      </a>
    </div>
    <div class="extra content">
      <a href="<%= @event.purchase_url %>" target="_blank">
        <i class="ticket icon"></i>
        <% if @event.price == 0 || @event.price.nil? %>
          Free
        <% else %>
        $<%= @event.price %> entry fee
        <% end %>
      </a>
    </div>
    <!-- TODO: all events will have places in the future, check if it's a one-off place -->
    <% unless @event.place.nil? %>
      <div class="extra content">
        <i class="calendar icon"></i>
            <%= link_to 'View All Events At This Venue', place_path(@event.place) %>
      </div>
    <% end %>
    <form action="<%= @event.purchase_url %>" target="_blank">
      <button class="ui blue fluid button" type="submit">
        I want to go to this.
      </button>
    </form>
  </div>
</div>

<script src="//load.sumome.com/" data-sumo-site-id="b718705fd70631f172a2537111f52585cef586b91418270b61487f82880ce672" async="async"></script>