config/routes.rb
Rails.application.routes.draw do

  resources :categories
  # devise_for :users
  resources :places
  resources :events
  get 'import/events', to: 'events#import', as: :import_events
  get 'import/places', to: 'places#import', as: :import_places
  match '/events/get_address_and_loc' => 'events#get_address_and_loc', :via => :post


  root 'pages#home'
  get 'pages/dates'
  get 'pages/user_index'
  get 'pages/sample_user'
  get 'pages/explore'
  get 'pages/dating'
  get 'pages/bundle_9786063511'
  get '/adventures', to: 'pages#adventures'
  get '/rec', to: 'pages#rec'
  get '/another', to: 'pages#another'
  get '/join', to: 'pages#join'
  get '/test', to: 'pages#test'
  get '/postcard', to: 'pages#postcard'

  # ANALYTICS DASHBOARD
  get '/dashboard', to: 'dashboard#index', as: :dashboard
  match '/dashboard/metrics' => 'dashboard#metrics', :via => :post

  # FRONT WEBHOOK
  match '/front/mirror' => 'front#mirror', :via => :post
  match '/front/bot' => 'front#bot', :via => :post
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :events, dependent: :nullify
  has_many :open_times, dependent: :destroy
  has_and_belongs_to_many :tags

  accepts_nested_attributes_for :events, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :open_times, allow_destroy: true, reject_if: :all_blank

  # Ghost attributes from form
  attr_accessor :full_address

  # takes an address string and returns all location fields
  geocoded_by :full_address, :latitude  => :lat, :longitude => :lng do |obj, result|
    if result.first
      geo = result.first
      obj.street = geo.street_address
      obj.city = geo.city
      obj.state = geo.state_code
      obj.zip = geo.postal_code
      obj.country = geo.country
      obj.neighborhood = geo.neighborhood
      obj.lat = geo.coordinates[0]
      obj.lng = geo.coordinates[1]
    end
  end

  after_validation :geocode, if: :geocode?

  # form validations
  validates :name, presence: true
  # validates :description, presence: true

  # image upload properties
  has_attached_file :image, styles: {
    medium: '400x300#',
    banner: '338x100#',
    tiny: '140x140>',
    mini: '80x80!'
  }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  # index search properties
  def self.search(search)
    where("name || description || neighborhood ILIKE ?", "%#{search}%")
  end

  # returns all event instances in the next two weeks
  def future_events
    instances = []
    Event.where(place: self).each do |e|
      instances << e.occurrences.where(date: Date.current..2.weeks.from_now)
    end
    instances.flatten!.sort_by(&:date) unless instances.empty?
  end

  # GEOCODING
  def address
    [street, city, state, zip, country].compact.join(', ')
  end

  def geocode?
    # if address was not changed
    if full_address == address
      return false
    end

    # if imported from facebook and has no full_address (param from form)
    if fb_id && full_address.nil?
      return false
    end

    return true
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    authenticate
    @places = Place.where(approved: true)
  end

  def import
    authenticate
    @places = Place.where(approved: false)
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @open_hours = Hash.new
    @place.open_times.each do |schedule|
      @open_hours[schedule.day] = "#{schedule.open_time.strftime('%l:%M %P')} - #{schedule.close_time.strftime('%l:%M %P')}"
    end
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    # if the place was unapproved, add it to our import blacklist
    unless @place.approved?
      Blacklist.create(fb_id: @place.fb_id, name: @place.name)
    end

    @place.destroy

    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :description, :full_address, :website, :phone_number, :image, :approved, :neighborhood, open_times_attributes: [:id, :day, :open_time, :close_time, :_destroy])
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_error_messages.html.erb
<% if @place.errors.any? %>
  <div class="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@place.errors.count, "error") %>.
    </div>
    <ul>
    <% @place.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/places/_form.html.erb
<div id="new-place-form">
  <div class="ui form">
    <%= simple_form_for @place, html: { multipart: true } do |f| %>
        <%= render 'error_messages' %>
        <div class="field">
          <%= f.label :image %><br>
          <%= f.file_field :image, html: { class: 'form-control' } %>
          <% if f.object.image? %>
              <br />
              <%= image_tag(f.object.image.url(:medium)) %><br />
              <em>Currently Uploaded Image</em>
          <% end %>
        </div>
        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: "ui input" %>
        </div>
        <div class="field">
          <%= f.label :description %><br>
          <%= f.text_area :description, class: "ui input" %>
        </div>
        <div class="field">
          <%= f.label 'Address' %>
          <%= f.text_field :full_address,
                           class: "ui labeled input",
                           placeholder: "795 Massachusetts Ave, Cambridge, MA 02139",
                           value: @place.address %>
        </div>
        <% unless @place.new_record? %>
          <div class="field">
            <%= f.label :neighborhood %><br>
            <%= f.text_field :neighborhood, class: "ui input" %>
          </div>
        <% end %>
        <div class="field">
          <%= f.label :website %>
          <div class="ui labeled input">
            <div class="ui label">
              http://
            </div>
            <%= f.text_field :website, :placeholder => "mywebsite.com" %>
          </div>
        </div>
        <div class="field">
          <%= f.label :phone_number %>
          <%= f.text_field :phone_number, class: "ui labeled input", :placeholder => "5558675309" %>
        </div>
        <%= f.simple_fields_for :open_times do |open_time| %>
            <%= render 'open_time_fields', :f => open_time %>
        <% end %>
        <div class='field links'>
          <%= link_to_add_association 'Add Open Hours', f, :open_times %>
        </div>
      <div class="field">
        <% unless @place.approved? %>
          <%= f.input :approved, as: :boolean %>
        <% end %>
      </div>
      <% if not @place.approved? %>
        <%= f.submit 'Approve', class: 'ui blue fluid button', name: 'approve' %>
      <% else %>
        <%= f.submit 'Create new place', class: 'ui blue fluid button', name: 'create' %>
      <% end %>
      <br/>
      <% unless @place.new_record? %>
        <%= link_to 'Delete', place_path(@place), :method => :delete, class: "ui blue fluid button" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/places/_header.html.erb
<div class="ui secondary fluid three item menu">
  <a class="ui item" href="#" id="search-icon">
    <i class="search icon"></i>
  </a>
  <a class="ui item hidden" href="#" id="remove-icon">
    <i class="remove icon"></i>
  </a>
  <a class="item" href="./">
    <%= image_tag("face.png", :class => "ui centered image mini") %>
  </a>
  <a class="ui item" href="/places/new">
    <i class="plus icon"></i>
  </a>
</div>

<div class="ui secondary menu hidden" id="search-form">
  <div class="centered item">
    <div class="ui icon input">
      <%= form_tag(places_path, :method => "get") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search Places" %>
      <%= submit_tag "Search" %>
      <% end %>
      <i class="search link icon"></i>
    </div>
  </div>
</div>

app/views/places/_new_place_header.html.erb
<div class="ui secondary fluid three item menu">
  <a class="ui item" href="./">
    <i class="remove icon"></i>
  </a>
  <a class="item" href="../">
    <%= image_tag("face.png", :class => "ui centered image mini") %>
  </a>
  <a class="ui item invisible" href="#">
    <i class="plus icon"></i>
  </a>
</div>

app/views/places/_open_time_fields.erb
<div class='nested-fields ui segment'>
  <%= f.input :day,
              collection: 0..6,
              label_method: ->(obj){ t(Date::DAYNAMES[obj]) },
              wrapper_html: { class: 'field' } %>
  <%= f.input :open_time, as: :time, minute_step: 15, ampm: true, wrapper_html: { class: 'field' } %>
  <%= f.input :close_time, as: :time, minute_step: 15, ampm: true, wrapper_html: { class: 'field' } %>
  <%= link_to_remove_association 'Remove', f %>
</div>

app/views/places/_place_header.html.erb
<div class="ui secondary fluid one item menu">
  <a class="item" href="http://www.joinferris.com/">
    <%= image_tag("logo-white-background.png", :class => "ui centered image tiny") %>
  </a>
</div>

<p class="headline">
  <a href="sms:16176827760&body=Hello">Text Ferris</a> to find something to do in Boston.
</p>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/import.html.erb
<% provide(:title, ' | Places') %>
<div class="ui padded grid stackable">
  <% @places.each do |place| %>
    <div class="four wide column">
      <div class="ui cards preview-card">
        <div class="card">
          <%= link_to image_tag(place.image.url(:banner), class: 'index-image'), place %>
          <div class="content">
            <div class="header"><%= link_to (place.name), place %></div>
            <div class="description">
              <%= truncate(place.description, length: 105, omission: '...') %>
            </div>
          </div>
          <div class="extra content">
            <span class="right floated">
              <button class="ui mini basic labeled icon button copy-to-clipboard" data-clipboard-text="<%= place.description %> More info here: www.joinferris.com/places/<%= place.id %>">
                <i class="copy icon"></i>
                Copy
              </button>
            </span>
            <span>
              <i class="globe icon"></i>
              <%= place.neighborhood %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
  var clipboard = new Clipboard('.copy-to-clipboard');
  clipboard.on('success', function(e) {
    console.info('Action:', e.action);
    console.info('Text:', e.text);
    console.info('Trigger:', e.trigger);

    e.clearSelection();
  });

  clipboard.on('error', function(e) {
      console.error('Action:', e.action);
      console.error('Trigger:', e.trigger);
  });
</script>

app/views/places/index.html.erb
<% provide(:title, ' | Places') %>
<%= render 'header' %>  
<div class="ui padded grid stackable">
  <% @places.each do |place| %>
    <div class="four wide column">
      <div class="ui cards preview-card">
        <div class="card">
          <%= link_to image_tag(place.image.url(:banner), class: 'index-image'), place %>
          <div class="content">
            <div class="header"><%= link_to (place.name), place %></div>
            <div class="description">
              <%= truncate(place.description, length: 105, omission: '...') %>
            </div>
          </div>
          <div class="extra content">
            <span class="right floated">
              <button class="ui mini basic labeled icon button copy-to-clipboard" data-clipboard-text="<%= place.description %> More info here: www.joinferris.com/places/<%= place.id %>">
                <i class="copy icon"></i>
                Copy
              </button>
            </span>
            <span>
              <i class="globe icon"></i>
              <%= place.neighborhood %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script>
  var clipboard = new Clipboard('.copy-to-clipboard');
  clipboard.on('success', function(e) {
    console.info('Action:', e.action);
    console.info('Text:', e.text);
    console.info('Trigger:', e.trigger);

    e.clearSelection();
  });

  clipboard.on('error', function(e) {
      console.error('Action:', e.action);
      console.error('Trigger:', e.trigger);
  });
</script>

app/views/places/new.html.erb
<% provide(:title, ' | Create New Place') %>
<%= render 'new_place_header' %>
<%= render 'form' %>

app/views/places/show.html.erb
<% provide(:title, ' | ' + @place.name) %>
<%= render 'place_header' %>
<div class="place-card">
  <div class="ui card">
    <div class="ui fluid image">
      <%= image_tag @place.image.url(:medium) %>
    </div>
    <div class="content">
      <p class="header"><%= @place.name %></p>
      <div class="description">
        <%= @place.description %>
      </div>
    </div>
    <% if @place.city? %>
        <div class="extra content">
          <a href="http://maps.google.com/?q=<%= @place.address %>" target="_blank">
            <i class="location arrow icon"></i>
            <% if @place.neighborhood? %>
                <%= @place.neighborhood %>
            <% else %>
                <%= @place.city if @place.city? %>
            <% end %>
          </a>
        </div>
    <% end %>
    <div class="extra content">
      <a href="<%= @place.website %>" target="_blank">
        <i class="linkify icon"></i>
        Visit Website
      </a>
    </div>
    <div class="extra content">
      <a href="tel:<%= @place.phone_number %>" target="_blank">
        <i class="phone icon"></i>
        Call Them
      </a>
    </div>
    <% unless @open_hours.empty? %>
        <div class="extra content ui accordion">
          <div class="title">
            <i class="dropdown icon"></i>
            Hours
          </div>
          <div class="content">
            <table class="ui very basic unstackable table transition hidden">
              <tbody>
              <tr>
                <td class = "collapsing">Monday:</td>
                <td class="right aligned">
                  <% if @open_hours.key?(1) %>
                      <%= @open_hours[1] %>
                  <% else %>
                      CLOSED
                  <% end %>
                </td>
              </tr>
              <tr>
                <td class = "collapsing">Tuesday:</td>
                <td class="right aligned">
                  <% if @open_hours.key?(2) %>
                      <%= @open_hours[2] %>
                  <% else %>
                      CLOSED
                  <% end %>
                </td>
              </tr>
              <tr>
                <td class = "collapsing">Wednesday:</td>
                <td class="right aligned">
                  <% if @open_hours.key?(3) %>
                      <%= @open_hours[3] %>
                  <% else %>
                      CLOSED
                  <% end %>
                </td>
              </tr>
              <tr>
                <td class = "collapsing">Thursday:</td>
                <td class="right aligned">
                  <% if @open_hours.key?(4) %>
                      <%= @open_hours[4] %>
                  <% else %>
                      CLOSED
                  <% end %>
                </td>
              </tr>
              <tr>
                <td class = "collapsing">Friday:</td>
                <td class="right aligned">
                  <% if @open_hours.key?(5) %>
                      <%= @open_hours[5] %>
                  <% else %>
                      CLOSED
                  <% end %>
                </td>
              </tr>
              <tr>
                <td class = "collapsing">Saturday:</td>
                <td class="right aligned">
                  <% if @open_hours.key?(6) %>
                      <%= @open_hours[6] %>
                  <% else %>
                      CLOSED
                  <% end %>
                </td>
              </tr>
              <tr>
                <td class = "collapsing">Sunday:</td>
                <td class="right aligned">
                  <% if @open_hours.key?(0) %>
                      <%= @open_hours[0] %>
                  <% else %>
                      CLOSED
                  <% end %>
                </td>
              </tr>
              </tbody>
            </table>
          </div>
        </div>
    <% end %>
    <% unless @place.future_events.nil? %>
    <div class="extra content ui accordion" id="place-events">
      <div class="title">
        <i class="dropdown icon"></i>
        Upcoming Events
      </div>
      <div class="content">
      <% @place.future_events.each do |instance| %>
        <div class="ui vertical segment">
          <%= link_to event_path(instance.event) do %>
            <div class="ui statistics">
              <div class="statistic left floated">
                <div class="label">
                  <%= instance.date.strftime('%b') %>
                </div>
                <div class="value" style="font-size: 3em;">
                  <%= instance.date.day %>
                </div>
              </div>
              <div>
                <div class="header"><%= instance.event.title %></div>
                <div class="event-subtitle">
                  <%= "#{instance.date.strftime('%a')}, #{instance.event.start_time.strftime('%l:%M %P')}" %>
                  <%= '- ' + instance.event.end_time.strftime('%l:%M %P')  unless instance.event.end_time.nil? %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

<script>
  $('.ui.accordion')
    .accordion()
  ;
</script>